import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const westmeath = localFont({
  src: "./fonts/Westmeath.ttf",
  display: "swap",
  variable: "--font-westmeath",
});

const centurygothic = localFont({
  src: "./fonts/CenturyGothicPaneuropeanRegular.ttf",
  display: "swap",
  variable: "--font-centurygothic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${westmeath.variable} ${inter.className}`}>{children}</body>
    </html>
  );
}
