// data_panitia.ts
import ketua from "../../public/about-us/ketua-wispril/ketua.jpg";

export const cardDataPersonalia = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Grace Evangeline Anastasia",
    title: "KETUA DIVISI",
    batch: "OS'22",
    division: "PSDM",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Prasetio Hidayat",
    title: "WAKIL KETUA DIVISI",
    batch: "KI'22",
    division: "PSDM",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Netania",
    title: "KETUA DIVISI",
    batch: "AK'22",
    division: "MSDM",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Reihana Je Aminata",
    title: "WAKIL KETUA DIVISI",
    batch: "AK'22",
    division: "MSDM",
  },
];

export const cardDataFundraising = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Rufaida Khairina",
    title: "KETUA DIVISI",
    batch: "BM'22",
    division: "SPONSORSHIP",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Muhammad Kahlil Gibran",
    title: "WAKIL KETUA DIVISI",
    batch: "GD'22",
    division: "SPONSORSHIP",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Naila Faridah Huda W",
    title: "KETUA DIVISI",
    batch: "OS'22",
    division: "ENTREPRENEURSHIP",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Wynneth Artdelyn Jees",
    title: "WAKIL KETUA DIVISI",
    batch: "DI'22",
    division: "ENTREPRENEURSHIP",
  },
];

export const cardDataRelasi = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Zalfa Dhia Lesmawan",
    title: "KETUA DIVISI",
    batch: "MS'22",
    division: "INTRAKAMPUS",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Syakilla Putri Nikita",
    title: "WAKIL KETUA DIVISI",
    batch: "BW'22",
    division: "INTRAKAMPUS",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Athala Rania Insyra",
    title: "KETUA DIVISI",
    batch: "ET'22",
    division: "EKSTRAKAMPUS",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Erlinta Putri Nariswari",
    title: "WAKIL KETUA DIVISI",
    batch: "EP'22",
    division: "EKSTRAKAMPUS",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Nadine Syahrany Levina Siregar",
    title: "SEKRETARIS DIVISI",
    batch: "FKK'22",
    division: "INTRAKAMPUS",
  },
];

export const cardDataSekretariat = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Firnindya Dyah Intan Larasati",
    title: "SEKRETARIS 1",
    batch: "TK'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Gabriela Deangela Sitanggang ",
    title: "SEKRETARIS 2",
    batch: "TK'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Rainy Larasati",
    title: "BENDAHARA 1",
    batch: "TM'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Mega Bhuana",
    title: "BENDAHARA 2",
    batch: "AK'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Muhammad Fath Al Faiz",
    title: "KETUA DIVISI ",
    batch: "GL'22",
    division: "PERIZINAN",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Nabiel Falih Utama",
    title: "WAKIL KETUA DIVISI",
    batch: "MS'22",
    division: "PERIZINAN",
  },
];

export const cardDataOperasional = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "M.Faddel Tonralipu Irham",
    title: "KETUA DIVISI",
    batch: "EB'22",
    division: "LOGISTIK",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Muhammad Naufal Kamil Hero",
    title: "WAKIL KETUA DIVISI",
    batch: "TA'22",
    division: "LOGISTIK",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Dewantoro Triatmojo",
    title: "KETUA DIVISI",
    batch: "IF'22",
    division: "IT",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Ahmad Naufal Ramadhan",
    title: "WAKIL KETUA DIVISI",
    batch: "IF'22",
    division: "IT",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Genio Wahyu Andreas",
    title: "KETUA DIVISI ",
    batch: "AE'22",
    division: "PRODUKSI",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Muhammad Zhafran Aku Hafizh",
    title: "WAKIL KETUA DIVISI ",
    batch: "GD'22",
    division: "PRODUKSI",
  },
];

export const cardDataAcara = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Darma Wangsa",
    title: "KETUA DIVISI",
    batch: "TA'22",
    division: "APPRECIATION",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Angelica Fira Arthasaskia",
    title: "WAKIL KETUA DIVISI",
    batch: "MB'22",
    division: "APPRECIATION",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Muhammad Guinnot Raid",
    title: "KETUA DIVISI",
    batch: "TF'22",
    division: "ENFEST",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Axl Sebastian",
    title: "WAKIL KETUA DIVISI",
    batch: "SI'22",
    division: "ENFEST",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Tarisha Zamita Pratama",
    title: "KETUA DIVISI",
    batch: "PWK'22",
    division: "EDUCATION",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Andrea Adeline Dewanto",
    title: "WAKIL KETUA DIVISI",
    batch: "TF'22",
    division: "EDUCATION",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Weka Samba Parabawa",
    title: "KETUA DIVISI",
    batch: "TA'22",
    division: "CHARITY AND SUSTAINABILITY CAMPAIGN",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Gina Enjel Lorensa",
    title: "WAKIL KETUA DIVISI",
    batch: "TL'22",
    division: "CHARITY AND SUSTAINABILITY CAMPAIGN",
  },
];

export const cardDataLapangan = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Pascal Rangga Prasetya",
    title: "DANLAP 1",
    batch: "TA'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Soulthan Omar Al Maghribby",
    title: "DANLAP 2",
    batch: "GL'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Vicink Alfresco Yusuf Caesar Al Anshar",
    title: "DANLAP 3",
    batch: "SI'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Claudia Dianelsa Adventin",
    title: "DANLAP 4",
    batch: "pwk'22",
    division: "",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Muhammad Dzaky Mahardika",
    title: "DANLAP 5",
    batch: "TM'22",
    division: "",
  },
];

export const cardDataKreatif = [
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Jesseline Carolee Sabas",
    title: "KETUA DIVISI",
    batch: "DI'22",
    division: "PROPAGANDA",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Qynara Amaris",
    title: "WAKIL KETUA DIVISI",
    batch: "DP'22",
    division: "PROPAGANDA",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Talita Aulia Zahara Iskandar",
    title: "KETUA DIVISI",
    batch: "KR'22",
    division: "PUBDOK",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Kania Jatiningsih Putri Azzahra",
    title: "WAKIL KETUA DIVISI",
    batch: "DI'22",
    division: "PUBDOK",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Farrel Fadlurrahman",
    title: "KETUA DIVISI",
    batch: "MK'22",
    division: "ARTISTIK",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Naufal Abiyan Wijaya",
    title: "WAKIL KETUA DIVISI",
    batch: "DKV'22",
    division: "ARTISTIK",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Sekar Arum Kusumaningsih",
    title: "KETUA DIVISI",
    batch: "KR'22",
    division: "MEDIA INFORMASI",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Guido Ogilvy Dwandra",
    title: "WAKIL KETUA DIVISI",
    batch: "DKV'22",
    division: "MEDIA INFORMASI",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Graciella Nava Anindya",
    title: "KETUA DIVISI",
    batch: "DKV'22",
    division: "DESAIN GRAFIS",
  },
  {
    frameColor: "yellow",
    photo: ketua.src,
    name: "Nur Assyifa Oktariyani",
    title: "WAKIL KETUA DIVISI",
    batch: "DKV'22",
    division: "DESAIN GRAFIS",
  },
];
